"""add order table in status column

Revision ID: 1a404d65afd8
Revises: b06824e20421
Create Date: 2024-07-08 15:41:48.002586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a404d65afd8'
down_revision: Union[str, None] = 'b06824e20421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderInfo', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('OrderInfo', 'status')
    # ### end Alembic commands ###
