"""add new column in productinfo table 

Revision ID: 468c6a7c7091
Revises: c32d7fede778
Create Date: 2024-07-02 17:53:29.931202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '468c6a7c7091'
down_revision: Union[str, None] = 'c32d7fede778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ProductInfo', sa.Column('u_id', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'ProductInfo', 'UserInfo', ['u_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ProductInfo', type_='foreignkey')
    op.drop_column('ProductInfo', 'u_id')
    # ### end Alembic commands ###
