"""delete discount_price

Revision ID: 86a175ad0821
Revises: 0640fbf5c50b
Create Date: 2024-07-19 15:02:20.938685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86a175ad0821'
down_revision: Union[str, None] = '0640fbf5c50b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ProductInfo', 'discount_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ProductInfo', sa.Column('discount_price', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
