"""add payment table in foreignkey

Revision ID: 897368a12f13
Revises: b10dcff16e31
Create Date: 2024-07-15 18:20:33.265089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '897368a12f13'
down_revision: Union[str, None] = 'b10dcff16e31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'PaymentInfo', 'UserInfo', ['user_id'], ['id'])
    op.create_foreign_key(None, 'PaymentInfo', 'OrderInfo', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'PaymentInfo', type_='foreignkey')
    op.drop_constraint(None, 'PaymentInfo', type_='foreignkey')
    # ### end Alembic commands ###
