"""add feedback table in foreignkey

Revision ID: ac6b1009864d
Revises: 468c6a7c7091
Create Date: 2024-07-02 17:56:51.283854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac6b1009864d'
down_revision: Union[str, None] = '468c6a7c7091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'FeedbackInfo', 'UserInfo', ['u_id'], ['id'])
    op.create_foreign_key(None, 'FeedbackInfo', 'ProductInfo', ['p_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'FeedbackInfo', type_='foreignkey')
    op.drop_constraint(None, 'FeedbackInfo', type_='foreignkey')
    # ### end Alembic commands ###
