"""add foreignkey in payment table

Revision ID: aeb095ba9871
Revises: 561302124153
Create Date: 2024-07-16 18:42:56.285107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeb095ba9871'
down_revision: Union[str, None] = '561302124153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DeliveryInfo', sa.Column('delivery_boy_id', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'DeliveryInfo', 'DeliveryBoyInfo', ['delivery_boy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'DeliveryInfo', type_='foreignkey')
    op.drop_column('DeliveryInfo', 'delivery_boy_id')
    # ### end Alembic commands ###
