"""change product table in price column

Revision ID: b06824e20421
Revises: c7120e5248cf
Create Date: 2024-07-04 17:04:15.778635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b06824e20421'
down_revision: Union[str, None] = 'c7120e5248cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProductInfo',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('hotel_id', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.String(length=100), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['CategoryInfo.id'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['HotelInfo.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['UserInfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('OrderInfo',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('delivery_address', sa.String(length=1000), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.String(length=100), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['ProductInfo.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['UserInfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'FeedbackInfo', 'ProductInfo', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'FeedbackInfo', type_='foreignkey')
    op.drop_table('OrderInfo')
    op.drop_table('ProductInfo')
    # ### end Alembic commands ###
