"""add new table Delivery_boy

Revision ID: bc17c32a9044
Revises: f9e6a2f5d4f0
Create Date: 2024-07-16 17:49:09.253016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc17c32a9044'
down_revision: Union[str, None] = 'f9e6a2f5d4f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
