"""add new table cart and some change in other table

Revision ID: c7120e5248cf
Revises: ac6b1009864d
Create Date: 2024-07-04 14:57:14.016316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7120e5248cf'
down_revision: Union[str, None] = 'ac6b1009864d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FeedbackInfo', sa.Column('user_id', sa.String(length=100), nullable=False))
    op.add_column('FeedbackInfo', sa.Column('product_id', sa.String(length=100), nullable=False))
    op.drop_constraint('FeedbackInfo_u_id_fkey', 'FeedbackInfo', type_='foreignkey')
    op.drop_constraint('FeedbackInfo_p_id_fkey', 'FeedbackInfo', type_='foreignkey')
    op.create_foreign_key(None, 'FeedbackInfo', 'ProductInfo', ['product_id'], ['id'])
    op.create_foreign_key(None, 'FeedbackInfo', 'UserInfo', ['user_id'], ['id'])
    op.drop_column('FeedbackInfo', 'u_id')
    op.drop_column('FeedbackInfo', 'p_id')
    op.add_column('OrderInfo', sa.Column('user_id', sa.String(length=100), nullable=False))
    op.alter_column('OrderInfo', 'delivery_address',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.create_foreign_key(None, 'OrderInfo', 'UserInfo', ['user_id'], ['id'])
    op.drop_column('OrderInfo', 'payment_method')
    op.drop_column('OrderInfo', 'status')
    op.drop_column('OrderInfo', 'order_date')
    op.add_column('ProductInfo', sa.Column('user_id', sa.String(length=100), nullable=True))
    op.drop_constraint('ProductInfo_u_id_fkey', 'ProductInfo', type_='foreignkey')
    op.create_foreign_key(None, 'ProductInfo', 'UserInfo', ['user_id'], ['id'])
    op.drop_column('ProductInfo', 'u_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ProductInfo', sa.Column('u_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ProductInfo', type_='foreignkey')
    op.create_foreign_key('ProductInfo_u_id_fkey', 'ProductInfo', 'UserInfo', ['u_id'], ['id'])
    op.drop_column('ProductInfo', 'user_id')
    op.add_column('OrderInfo', sa.Column('order_date', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('OrderInfo', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('OrderInfo', sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'OrderInfo', type_='foreignkey')
    op.alter_column('OrderInfo', 'delivery_address',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('OrderInfo', 'user_id')
    op.add_column('FeedbackInfo', sa.Column('p_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('FeedbackInfo', sa.Column('u_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'FeedbackInfo', type_='foreignkey')
    op.drop_constraint(None, 'FeedbackInfo', type_='foreignkey')
    op.create_foreign_key('FeedbackInfo_p_id_fkey', 'FeedbackInfo', 'ProductInfo', ['p_id'], ['id'])
    op.create_foreign_key('FeedbackInfo_u_id_fkey', 'FeedbackInfo', 'UserInfo', ['u_id'], ['id'])
    op.drop_column('FeedbackInfo', 'product_id')
    op.drop_column('FeedbackInfo', 'user_id')
    # ### end Alembic commands ###
