"""add product table in discount price

Revision ID: cb34769b447a
Revises: aeb095ba9871
Create Date: 2024-07-19 14:32:19.338949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb34769b447a'
down_revision: Union[str, None] = 'aeb095ba9871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ProductInfo', sa.Column('discount_price', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ProductInfo', 'discount_price')
    # ### end Alembic commands ###
