"""add discount price

Revision ID: dbfd769dc617
Revises: 86a175ad0821
Create Date: 2024-07-19 15:08:18.588618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbfd769dc617'
down_revision: Union[str, None] = '86a175ad0821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ProductInfo', sa.Column('discount_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ProductInfo', 'discount_price')
    # ### end Alembic commands ###
